print("Here are the tasks:","Addition","Subtraction","Multiplication","Division","Powers","Floor division","Modular arithmetic",sep="\n")
print("Addition a + b")
a = float(input("a: "))
b = float(input("b: "))
print(a," + ",b," = ",a+b,sep="")
print("Subtraction a - b")
a = float(input("a: "))
b = float(input("b: "))
print(a," - ",b," = ",a-b,sep="")
print("Multiplication a x b")
a = float(input("a: "))
b = float(input("b: "))
print(a," x ",b," = ",a*b,sep="")
print("Division a ÷ b")
a = float(input("a: "))
b = float(input("b: "))
print(a," ÷ ",b," = ",a/b,sep="")
print("Powers a^b")
a = float(input("a: "))
b = float(input("b: "))
print(a,"^",b," = ",a**b,sep="")
print("Floor division a / b (no remainder)")
a = float(input("a: "))
b = float(input("b: "))
print(a," / b ≈ ",a//b,sep="")
print("Modular arithmetic a (mod b) (no remainder)")
a = float(input("a: "))
b = float(input("b: "))
print(a," ≡ ",a%b," (mod ",b,")",sep="")